### ISSUE TITLE
Can't open paid text message.

### ISSUE THREAD

**Issue by lucasfloriani** [getZION/react-native#49]

**Comment by lucasfloriani** [comment]
@mohamedsamara can you provide more information about this issue? What is the main screen that this issue occurs?

**Comment by mohamedsamara** [comment]
@lucasfloriani users can send paid text messages in chat. It is commented out right now because it was not working. When user "A" send paid text message to user "B" and user "B" pay for the message they still can't see the text message even though they paid for it. You can see the original code in the fork repo.
